# Generated by Django 4.2.2 on 2023-07-10 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='place',
            new_name='destination',
        ),
    ]
